image: docker:stable

variables:
  LATEST_VER: bagesh2050/hello-world-java:0.0.5.RELEASE

stages:
  - Build image
  - Push to Docker Hub

docker build:
  stage: Build image
  script:
  - docker info
  - docker build -t $LATEST_VER .

docker push:
  stage: Push to Docker Hub
  only:
  - master
  script:
  - docker login -u "bagesh2050" -p "B$docker2050"
  - docker push $LATEST_VER && docker image rm $LATEST_VER