image: docker:18-git

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  LATEST_VER: bagesh2050/hello-world-java:0.0.6.RELEASE
  VERSION: 0.0.6.RELEASE
  
services:
  - docker:18-dind
  
stages:
  - Build image
  - deploy

docker build:
  stage: Build image
  script:
    - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin
    - docker build -t $LATEST_VER .
    - docker push $LATEST_VER && docker image rm $LATEST_VER
  when: manual
  only:
    - master
  
deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    #- kubectl version
    #- kubectl config set-cluster k8s --server="${SERVER}"
    #- kubectl config set clusters.k8s.certificate-authority-data ${CERTIFICATE_AUTHORITY_DATA}
    #- kubectl config set-credentials gitlab --token="${USER_TOKEN}"
    #- kubectl config set-context default --cluster=k8s --user=gitlab
    #- kubectl config use-context default
    - sed -i "s/<VERSION>/${VERSION}/g" deployment.yaml
    - kubectl apply -f deployment.yaml
  environment:
    name: production
    url: https://example.com/