image: docker:18-git

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  LATEST_VER: bagesh2050/hello-world-java:0.0.5.RELEASE
  
services:
  - docker:18-dind
  
stages:
  - Build image
  - Push to Docker Hub

docker build:
  stage: Build image
  script:
  - docker info
  - docker build -t $LATEST_VER .

docker push:
  stage: Push to Docker Hub
  only:
  - master
  script:
  - echo "$MY_PASSWORD" | docker login --username bagesh2050 --password-stdin
  - docker push $LATEST_VER && docker image rm $LATEST_VER