image: docker:18-git

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  LATEST_VER: bagesh2050/hello-world-java:0.0.6.RELEASE
  
services:
  - docker:18-dind
  
stages:
  - Build image
  - deploy

docker build:
  stage: Build image
  script:
    - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin
    - docker build -t $LATEST_VER .
    - docker push $LATEST_VER && docker image rm $LATEST_VER
  when: manual
  only:
    - master
  
deploy:
  stage: deploy
  #image: dtzar/helm-kubectl
  script:
    - kubectl apply -f deployment.yaml
    