apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-java
  labels:
    app: hello-world-java
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-java
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: hello-world-java
    spec:
      containers:
      - name: hello-world-java
        image: bagesh2050/hello-world-java:0.0.11.RELEASE
        ports:
        - containerPort: 5000
---    
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: NodePort
  selector:
    app: hello-world-java
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30001